// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAllj13SLyd-dRPGDhsp6Cnvzrzs4MqRWM',
    appId: '1:839780198148:web:b0187cabcbccf079e35251',
    messagingSenderId: '839780198148',
    projectId: 'echo-verse-de5dc',
    authDomain: 'echo-verse-de5dc.firebaseapp.com',
    storageBucket: 'echo-verse-de5dc.appspot.com',
    measurementId: 'G-BZHLFJ2TS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd0KfnlVyOtjZOuh58itNfPQ6qorzsw4c',
    appId: '1:839780198148:android:7379a4828a1b5aefe35251',
    messagingSenderId: '839780198148',
    projectId: 'echo-verse-de5dc',
    storageBucket: 'echo-verse-de5dc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAllj13SLyd-dRPGDhsp6Cnvzrzs4MqRWM',
    appId: '1:839780198148:web:2442fc648d352bf5e35251',
    messagingSenderId: '839780198148',
    projectId: 'echo-verse-de5dc',
    authDomain: 'echo-verse-de5dc.firebaseapp.com',
    storageBucket: 'echo-verse-de5dc.appspot.com',
    measurementId: 'G-NVMC2GDGB2',
  );
}
